version: "3"

services:

  db:
    image: influxdb:1.8
    container_name: influxdb
    ports:
      - 8086:8086
    volumes:
      - ./influxdb:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=${INFLUXDB_HOST}
      - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}
    networks:
      - symfony

  web:
    image: nginx
    volumes:
      - ./docker/conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    ports:
      - 80:80
    restart: always
    depends_on:
      - composer
      - php
      - db
    networks:
      - symfony
  php:
    build: docker/conf/php
    restart: always
    volumes:
      - .:/var/www/html
    networks:
      - symfony

  composer:
    build: docker/conf/php
    volumes:
      - .:/var/www/html
    command: ['composer', 'install', '--ignore-platform-reqs', '--ansi', '--no-interaction']

networks:
  symfony:
    driver: bridge
